# Generated by Django 5.1.2 on 2024-10-09 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anchorsapp', '0002_alter_anchor_options_alter_category_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='bg_color',
            field=models.CharField(default='#1461f6', max_length=150, verbose_name='Color de fondo'),
        ),
    ]
