# Generated by Django 5.1.2 on 2024-10-12 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anchorsapp', '0004_anchor_user_category_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='bg_color',
            field=models.CharField(default='#0d1117', max_length=150, verbose_name='Color de fondo'),
        ),
    ]
