# Generated by Django 5.1.2 on 2024-10-20 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anchorsapp', '0005_alter_category_bg_color'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anchor',
            name='link',
            field=models.URLField(max_length=250, verbose_name='Enlace'),
        ),
    ]
